export const projects = [
  {
    title: 'Automated Testing Framework',
    description: "A suite of automated tests for an E-Bank using Selenium and TestNG.",
      image: '/images/7.png',
      tags: ['Selenium', 'Java', 'TestNG'],
    code: 'https://github.com/zakjanzi/E2E-Testing-Framework',
    live: '',
    id: 'tests',
  },
  {
    title: 'A Python Scraper',
    description: "A script that scrapes the value of the LBP against the USD at the shadow market rate, then stores it in a DB.",
      image: '/images/6.png',
      tags: ['Python', 'AWS Lambda', 'MongoDB', 'Docker'],
    code: 'https://github.com/zakjanzi/lira-rate-scraper',
    live: 'https://zak-jobify.netlify.app/landing',
    id: 'scraper',
  },
  {
    title: 'A MERN App',
    description: "A MERN app & its automated framework.",
      image: '/images/1.webp',
      tags: ['MERN', 'Cypress', 'REST-Assured', 'JUnit'],
    code: 'https://github.com/zakjanzi/jobify-app',
    live: 'https://jobify-yzhh.onrender.com/',
    id: 0,
  },
  {
    title: 'A Company Site',
    description:"A static website for a Parkour & Gymnastics gym. ",
    image: '/images/2.gif',
    tags: ['HTML', 'SCSS', '🍦JavaScript'],
    code: 'https://github.com/zakjanzi/team-adrenaline-website',
    live: "https://teamadrenaline.me",
    id: 1,
  },
  {
    title: 'A Cryptocurrency Dashboard',
    description: "A slightly more aesthetic version of coinmarketcap. Followed the SSR design pattern.",
    image: '/images/4.gif',
    tags: ['Node.js', 'Next.js 13','Crypto-Compare API',],
    code: 'https://github.com/zakjanzi/coinmarketcap_clone',
    live: 'https://zak-coinmarketcapclone.netlify.app/',
    id: 3,
  },
  {
    title: 'Conway\u0027s game of life',
    description: "Conway’s Game of Life cellular automata simulation in JavaScript using the p5.js library.",
    image: '/images/3.gif',
    tags: ['🍦JavaScript','p5.js'],
    code: ' https://github.com/zakjanzi/Conways-Game-of-Life',
    live: 'https://zak-gameoflife.netlify.app/',
    id: 2,
  },

  // {
  //   title: 'Metamask Login Button',
  //   description: "A dApp login button using the Metamask API.",
  //   image: '/images/5.PNG',
  //   tags: ['🍦JavaScript', 'Metamask API'],
  //   code: 'https://github.com/zakjanzi/metamask_login',
  //   live: 'https://zak-connectwalletbutton.netlify.app/',
  //   id: 4,
  // },
];

// export const TimeLineData = [
//   { year: 2020, text: 'Started by learning language syntax. I learned Python basics first, but then decided to go down the JavaScript route.', },
//   { year: 2021, text: 'Studied theoretical aspects of web development. Learned about the web and its protocols, then dove into design patterns and focused on JavaScript fundamentals. Worked as a manual QA tester in parallel.', },
//   { year: 2022, text: 'After spending time on the front-end, I finally built my first CRUD app. I also experimented with RESTful APIs (as well as testing tools like Postman and Cypress). This is where I combined all the knowledge acquired the past couple years to start actually building and deploying stuff.', },
//   { year: 2023, text: 'I think it\u0027s about time I start using TypeScript.', },
// ];